# Dependencies
markdown                 : kramdown
theme                    : minima

# Permalink
permalink                : /blog/:year/:month/:day/:title

# Setup
title                    : CB.Amedjonekou
name                     : CB.Amedjonekou, L33T God.
tagline                  : 'CB Amedjonekou'
description              : Some cool *** detailing why I am the ***. Birth of a Legend - @Densetsu
url                      : https://cbamedjonekou.github.io/

# Where things are
sass:
    sass_dir             : _sass

collections:
    current-projects:
        output: true
        permalink: /projects/:path
    completed-projects:
        output: true
        permalink: /projects/:path


